plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-92
    config:
      file: .rubocop.yml
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  scss-lint:
    enabled: true
exclude_patterns:
  - "spec/"
  - "!spec/support/helpers"
  - "app/assets/stylesheets/bootstrap/"
  - "app/javascript/vendor/"
  - "db/schema.rb"
  - "db/seeds.rb"
  - "db/migrate/"