plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-79
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  reek:
    enabled: true
  scss-lint:
    enabled: true
