AllCops:
  Exclude:
    - '.pryrc'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/tasks/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/RescueModifier:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/MethodLength:
  Max: 15

Style/FormatStringToken:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/EmptyMethod:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false