AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '.pryrc'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/tasks/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/RescueModifier:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/MethodLength:
  Max: 15

Style/FormatStringToken:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/EmptyMethod:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false


  #### new

  Layout/SpaceBeforeBrackets:
  Enabled: true
Lint/AmbiguousAssignment:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/SwapValues:
  Enabled: true