version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1
jobs:
  build:
    working_directory: ~/preserva-app
    docker:
      - image: cimg/ruby:3.0.4-browsers
        environment:
          RAILS_ENV: test
          HOSTNAME: localhost
          PGHOST: localhost
          PGUSER: preservar-app
          BUNDLER_VERSION: 2.2.4
          PARALLEL_WORKERS: 1
      - image: circleci/postgres:12.5
        environment:
          POSTGRES_USER: preservar-app
          POSTGRES_DB: preservar_test
          POSTGRES_PASSWORD: "password"
    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: Install PostgreSQL
          command: sudo apt install -y postgresql-client || true

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Install Bundler 2
          command: gem install bundler

      - restore_cache:
          name: Restore bundle cache
          keys:
            - bundle-preservar-app-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Gems
          command: bundle install --path vendor/bundle
      - save_cache:
          name: Store bundle cache
          key: bundle-preservar-app-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Set up database
          command: RAILS_LOG_LEVEL=info bundle exec rake db:setup

      - run:
          name: Pre-install Geckodriver
          command: bundle exec rake webdrivers:geckodriver:update

      - run:
          name: Pre-install Chromedriver
          command: bundle exec rake webdrivers:chromedriver:update

      - run:
          name: Run Rails tests
          command: bundle exec bin/rspec

      - store_artifacts:
          path: tmp/screenshots
          destination: capybara-screenshots

      - store_artifacts:
          path: log/test.log
          destination: test.log