default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL_SIZE") { 5 } %>

development:
  <<: *default
  host: /tmp
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  database: preservar_development

test:
  <<: *default
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  database: preservar_test

production:
  url: <%= ENV['DATABASE_URL'] %>